version: '3.3'

services:

  application:
    image:
      application-container
    container_name:
      application-container
    ports:
      - 80:80
    depends_on:
      - database
      - redis
      - rabbitmq3
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/app_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=qwerty009
      - SPRING_RABBITMQ_HOST=rabbitmq
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  database:
    image:
      postgres
    container_name:
      database
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty009
    volumes:
      - pgdata:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"


  rabbitmq3:
    image:
      rabbitmq:3.6-management
    container_name:
      rabbitmq-container
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  pgdata:
    external: true
  redis-volume:
    external: true


