POST http://localhost:8081/saveMessage
Content-Type: application/json

{
  "text": "Hi",
  "userId": "1",
  "roomId": "2"
}
###
POST http://localhost:8081/saveUser
Content-Type: application/json

{
"firstName": "anastasia",
  "lastName": "semenova",
  "login": "smchk",
  "email": "smchk@gmail.com",
  "password": "qwerty007",
  "role": "ROLE_USER"
}
###
POST http://localhost:8081/saveUser
Content-Type: application/json

{
  "firstName": "milana",
  "lastName": "amirova",
  "login": "milaamir",
  "email": "mil@gmail.com",
  "password": "qwerty007",
  "role": "ROLE_USER"
}
###
POST http://localhost:8081/addRoom
Content-Type: application/json

{

}
